//+------------------------------------------------------------------+
//|                                              FirebaseUploader.mq5|
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Generated by AI Studio"
#property link      ""
#property version   "1.01"

#include <Generic\HashMap.mqh>

input string FirebaseProjectId = "knowledgeable-cinema-nrwfn"; // Firebase Project ID
input string DatabaseId = "ai-studio-2d3e08bf-8948-4861-b08b-89d8c8b49d07"; // Firestore Database ID (often "(default)")
input string WebApiKey = "AIzaSyBWYePGj3NRpvbT9GaP3DZNI3R_ygSuq-A";         // Firebase Web API Key
input int UploadIntervalSeconds = 60; // Upload Check Interval (seconds)

string idToken = "";
string localId = "";

datetime g_last_time = 0;
ulong g_max_ticket = 0;
string RECORD_FILE = "FirebaseUploader_Record.txt";

double g_peak_equity = 0;
double g_max_drawdown_val = 0;
double g_max_drawdown_pct = 0;
double g_avg_hold_seconds = 0;
bool g_stats_needs_upload = true;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   if(FirebaseProjectId == "" || WebApiKey == "") {
      Print("Please fill in all Firebase inputs.");
      return INIT_PARAMETERS_INCORRECT;
   }

   // Create Force Reupload Button
   ObjectCreate(0, "BtnForceUpload", OBJ_BUTTON, 0, 0, 0);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_CORNER, CORNER_LEFT_LOWER);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_XDISTANCE, 20);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_YDISTANCE, 20);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_XSIZE, 120);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_YSIZE, 30);
   ObjectSetString(0, "BtnForceUpload", OBJPROP_TEXT, "Force Reupload");
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_COLOR, clrBlack);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_BGCOLOR, clrLightGray);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_SELECTABLE, 0);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_HIDDEN, 0);
   ObjectSetInteger(0, "BtnForceUpload", OBJPROP_ZORDER, 100);
   ChartRedraw(0);

   // Load previous record if exists
   LoadRecord();
   
   // Calculate historical drawdown based on balance
   CalcHistoricalDrawdown();

   // Initial sync
   SyncDeals();
   
   // Ensure stats upload initially
   if(g_stats_needs_upload) {
      UploadAccountStats();
      g_stats_needs_upload = false;
   }

   // Set timer for continuous sync
   EventSetTimer(UploadIntervalSeconds);
   return INIT_SUCCEEDED;
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   EventKillTimer();
   ObjectDelete(0, "BtnForceUpload");
  }

//+------------------------------------------------------------------+
//| OnTick function (To check real-time equity drawdown)             |
//+------------------------------------------------------------------+
void OnTick()
  {
   CheckLiveDrawdown();
  }

//+------------------------------------------------------------------+
//| ChartEvent function                                              |
//+------------------------------------------------------------------+
void OnChartEvent(const int id,
                  const long &lparam,
                  const double &dparam,
                  const string &sparam)
  {
   if(id == CHARTEVENT_OBJECT_CLICK && sparam == "BtnForceUpload") {
      Print("Force Reupload triggered by user.");
      ObjectSetInteger(0, "BtnForceUpload", OBJPROP_STATE, 0); // Reset button state
      
      // Reset state variables
      g_last_time = 0;
      g_max_ticket = 0;
      
      // Delete record file
      FileDelete(RECORD_FILE);
      Print("Local record file deleted. Uploading all history...");
      
      CalcHistoricalDrawdown();
      
      // Trigger sync
      SyncDeals();
      UploadAccountStats();
      ChartRedraw(0);
   }
  }

//+------------------------------------------------------------------+
//| Expert timer function                                            |
//+------------------------------------------------------------------+
void OnTimer()
  {
   SyncDeals();
   
   if(g_stats_needs_upload) {
      UploadAccountStats();
      g_stats_needs_upload = false;
   }
  }

//+------------------------------------------------------------------+
//| Load Record from File                                            |
//+------------------------------------------------------------------+
void LoadRecord()
  {
   if(FileIsExist(RECORD_FILE)) {
      int handle = FileOpen(RECORD_FILE, FILE_READ|FILE_TXT|FILE_ANSI);
      if(handle != INVALID_HANDLE) {
         string content = FileReadString(handle);
         string parts[];
         if(StringSplit(content, ',', parts) == 2) {
            g_last_time = (datetime)StringToInteger(parts[0]);
            g_max_ticket = StringToInteger(parts[1]);
            Print("Loaded record: last_time=", g_last_time, " max_ticket=", g_max_ticket);
         }
         FileClose(handle);
      }
   } else {
      Print("No previous local record found. Will upload all history.");
      g_last_time = 0;
      g_max_ticket = 0;
   }
  }

//+------------------------------------------------------------------+
//| Save Record to File                                              |
//+------------------------------------------------------------------+
void SaveRecord()
  {
   int handle = FileOpen(RECORD_FILE, FILE_WRITE|FILE_TXT|FILE_ANSI);
   if(handle != INVALID_HANDLE) {
      string content = IntegerToString((long)g_last_time) + "," + IntegerToString(g_max_ticket);
      FileWriteString(handle, content);
      FileClose(handle);
   }
  }

//+------------------------------------------------------------------+
//| Sync Deals                                                       |
//+------------------------------------------------------------------+
void SyncDeals()
  {
   // Use g_last_time to limit history selection scope
   datetime startTime = g_last_time;
   if (startTime > 0) {
      // Just subtract a bit of time to ensure we don't miss deals happening exactly at that second.
      startTime -= 1; 
   }
   
   if(!HistorySelect(startTime, TimeCurrent())) {
      Print("HistorySelect failed.");
      return;
   }
   
   int totalDeals = HistoryDealsTotal();
   bool hasNew = false;
   
   for(int i=0; i<totalDeals; i++) {
      ulong ticket = HistoryDealGetTicket(i);
      if(ticket > 0) {
         // Only upload if it's a truly new ticket 
         if(ticket > g_max_ticket) {
            if(UploadDeal(ticket)) {
               datetime dealTime = (datetime)HistoryDealGetInteger(ticket, DEAL_TIME);
               if(dealTime > g_last_time) g_last_time = dealTime;
               if(ticket > g_max_ticket) g_max_ticket = ticket;
               hasNew = true;
            } else {
               Print("Failed to upload deal: ", ticket, ". Stopping sync loop to retry next time.");
               break; // Stop and retry later on failure to maintain sequential integrity
            }
         }
      }
   }
   
   if(hasNew) {
      SaveRecord();
      Print("Sync complete. New state written to record file.");
   }
  }

//+------------------------------------------------------------------+
//| Upload a single deal to Firestore                                |
//+------------------------------------------------------------------+
bool UploadDeal(ulong ticket)
  {
   long type = HistoryDealGetInteger(ticket, DEAL_TYPE);
   double volume = HistoryDealGetDouble(ticket, DEAL_VOLUME);
   double price = HistoryDealGetDouble(ticket, DEAL_PRICE);
   long time_msc = HistoryDealGetInteger(ticket, DEAL_TIME_MSC);
   double profit = HistoryDealGetDouble(ticket, DEAL_PROFIT);
   double commission = HistoryDealGetDouble(ticket, DEAL_COMMISSION);
   double swap = HistoryDealGetDouble(ticket, DEAL_SWAP);
   string symbol = HistoryDealGetString(ticket, DEAL_SYMBOL);
   long magic = HistoryDealGetInteger(ticket, DEAL_MAGIC);
   
   string dbId = DatabaseId;
   if(dbId == "") dbId = "(default)";

   long account = AccountInfoInteger(ACCOUNT_LOGIN);
   string docId = IntegerToString(account) + "_" + IntegerToString(ticket);

   string url = "https://firestore.googleapis.com/v1/projects/" + FirebaseProjectId + "/databases/" + dbId + "/documents/deals/" + docId + "?key=" + WebApiKey;
   string headers = "Content-Type: application/json\r\n";
   
   // Build the Firestore Document JSON format
   string json = "{";
   json += "\"fields\": {";
   json += "\"account\": {\"integerValue\": \"" + IntegerToString(account) + "\"},";
   json += "\"ticket\": {\"stringValue\": \"" + IntegerToString(ticket) + "\"},";
   json += "\"type\": {\"integerValue\": \"" + IntegerToString(type) + "\"},";
   json += "\"volume\": {\"doubleValue\": " + DoubleToString(volume, 2) + "},";
   json += "\"price\": {\"doubleValue\": " + DoubleToString(price, 5) + "},";
   json += "\"time\": {\"integerValue\": \"" + IntegerToString(time_msc) + "\"},";
   json += "\"profit\": {\"doubleValue\": " + DoubleToString(profit, 2) + "},";
   json += "\"commission\": {\"doubleValue\": " + DoubleToString(commission, 2) + "},";
   json += "\"swap\": {\"doubleValue\": " + DoubleToString(swap, 2) + "},";
   json += "\"symbol\": {\"stringValue\": \"" + symbol + "\"},";
   json += "\"magic\": {\"integerValue\": \"" + IntegerToString(magic) + "\"},";
   json += "\"isPublic\": {\"booleanValue\": true},";
   
   long updated_at = (long)TimeCurrent() * 1000;
   json += "\"updatedAt\": {\"integerValue\": \"" + IntegerToString(updated_at) + "\"}";
   
   json += "}"; // end fields
   json += "}"; // end doc

   char postData[];
   char result[];
   string resultHeaders;
   StringToCharArray(json, postData, 0, StringLen(json), CP_UTF8);
   
   int res = WebRequest("PATCH", url, headers, 10000, postData, result, resultHeaders);
   
   if(res == 200) {
      Print("Deal ", ticket, " uploaded.");
      return true;
   } else {
      Print("Failed to upload deal ", ticket, ", code: ", res);
      Print(CharArrayToString(result));
      return false;
   }
  }

//+------------------------------------------------------------------+
//| Calculate Historical Balance Drawdown                            |
//+------------------------------------------------------------------+
void CalcHistoricalDrawdown()
  {
   if(!HistorySelect(0, TimeCurrent())) return;
   
   int total = HistoryDealsTotal();
   double balance = 0;
   double max_bal = 0;
   double max_dd_val = 0;
   double max_dd_pct = 0;
   bool is_first = true;
   
   for(int i=0; i<total; i++) {
      ulong ticket = HistoryDealGetTicket(i);
      long type = HistoryDealGetInteger(ticket, DEAL_TYPE);
      double net = HistoryDealGetDouble(ticket, DEAL_PROFIT) + HistoryDealGetDouble(ticket, DEAL_COMMISSION) + HistoryDealGetDouble(ticket, DEAL_SWAP);
      
      if(is_first) {
         balance = net;
         max_bal = net > 0 ? net : 0;
         is_first = false;
         continue;
      }

      if(type == DEAL_TYPE_BALANCE) { 
         balance += net;
         max_bal += net; // adjust peak for deposits/withdrawals
      } else {
         balance += net;
         if(balance > max_bal) {
            max_bal = balance;
         } else {
            double dd = max_bal - balance;
            if(dd > max_dd_val) max_dd_val = dd;
            double pct = (max_bal > 0) ? ((dd / max_bal) * 100.0) : 0;
            if(pct > max_dd_pct) max_dd_pct = pct;
         }
      }
   }
   
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   g_peak_equity = MathMax(balance, max_bal);
   if (equity > g_peak_equity) g_peak_equity = equity;
   
   g_max_drawdown_val = max_dd_val;
   g_max_drawdown_pct = max_dd_pct;
   
   double total_hold_seconds = 0;
   int hold_count = 0;
   CHashMap<long, datetime> pos_in_times;
   
   for(int i=0; i<total; i++) {
      ulong tckt = HistoryDealGetTicket(i);
      long entry = HistoryDealGetInteger(tckt, DEAL_ENTRY);
      long pos_id = HistoryDealGetInteger(tckt, DEAL_POSITION_ID);
      datetime dt = (datetime)HistoryDealGetInteger(tckt, DEAL_TIME);
      
      if(entry == DEAL_ENTRY_IN) {
         datetime existing_time = 0;
         if(!pos_in_times.TryGetValue(pos_id, existing_time)) {
            pos_in_times.Add(pos_id, dt);
         }
      } else if(entry == DEAL_ENTRY_OUT || entry == DEAL_ENTRY_INOUT || entry == DEAL_ENTRY_OUT_BY) {
         datetime time_in = 0;
         if(pos_in_times.TryGetValue(pos_id, time_in)) {
            if(dt > time_in) {
               total_hold_seconds += (double)(dt - time_in);
               hold_count++;
            }
         }
      }
   }
   if(hold_count > 0) g_avg_hold_seconds = total_hold_seconds / hold_count;
   else g_avg_hold_seconds = 0;
   
   Print("Hist DD% calculated: ", g_max_drawdown_pct, " AvgHold: ", g_avg_hold_seconds);
  }

//+------------------------------------------------------------------+
//| Check Live Equity Drawdown                                       |
//+------------------------------------------------------------------+
void CheckLiveDrawdown()
  {
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   
   if(equity < balance) {
      double dd = balance - equity;
      bool updated = false;
      if(dd > g_max_drawdown_val + 0.01) { // 0.01 tolerance
         g_max_drawdown_val = dd;
         updated = true;
      }
      double pct = (balance > 0) ? ((dd / balance) * 100.0) : 0;
      if(pct > g_max_drawdown_pct + 0.0001) { // small tolerance
         g_max_drawdown_pct = pct;
         updated = true;
      }
      
      if(updated) {
         g_stats_needs_upload = true;
      }
   }
  }

//+------------------------------------------------------------------+
//| Upload Account Stats (Max Drawdown)                              |
//+------------------------------------------------------------------+
void UploadAccountStats()
  {
   string dbId = DatabaseId;
   if(dbId == "") dbId = "(default)";

   long account = AccountInfoInteger(ACCOUNT_LOGIN);
   string docId = IntegerToString(account) + "_stats";

   string url = "https://firestore.googleapis.com/v1/projects/" + FirebaseProjectId + "/databases/" + dbId + "/documents/accounts/" + docId + "?key=" + WebApiKey;
   string headers = "Content-Type: application/json\r\n";
   
   string broker = AccountInfoString(ACCOUNT_COMPANY);
   string server = AccountInfoString(ACCOUNT_SERVER);
   StringReplace(broker, "\"", "\\\"");
   StringReplace(server, "\"", "\\\"");

   // Build the Firestore Document JSON format
   string json = "{";
   json += "\"fields\": {";
   json += "\"account\": {\"integerValue\": \"" + IntegerToString(account) + "\"},";
   json += "\"maxDrawdown\": {\"doubleValue\": " + DoubleToString(g_max_drawdown_val, 2) + "},";
   json += "\"maxDrawdownPct\": {\"doubleValue\": " + DoubleToString(g_max_drawdown_pct, 4) + "},";
   json += "\"broker\": {\"stringValue\": \"" + broker + "\"},";
   json += "\"server\": {\"stringValue\": \"" + server + "\"},";
   json += "\"avgHoldSeconds\": {\"doubleValue\": " + DoubleToString(g_avg_hold_seconds, 0) + "}";
   json += "}"; // end fields
   json += "}"; // end doc

   char postData[];
   char result[];
   string resultHeaders;
   StringToCharArray(json, postData, 0, StringLen(json), CP_UTF8);
   
   int res = WebRequest("PATCH", url, headers, 10000, postData, result, resultHeaders);
   
   if(res == 200) {
      Print("Account stats uploaded successfully.");
   } else {
      Print("Failed to upload account stats, code: ", res);
      Print(CharArrayToString(result));
   }
  }


